DROP TABLE IF EXISTS sessions;
DROP TABLE IF EXISTS comments;
DROP TABLE IF EXISTS tracks;
DROP TABLE IF EXISTS band_invites;
DROP TABLE IF EXISTS band_members;
DROP TABLE IF EXISTS bands;
DROP TABLE IF EXISTS users;
