ALTER TABLE bands ALTER COLUMN created_by SET NOT NULL;
ALTER TABLE tracks ALTER COLUMN uploaded_by SET NOT NULL;
ALTER TABLE comments ALTER COLUMN user_id SET NOT NULL;
ALTER TABLE band_files ALTER COLUMN uploaded_by SET NOT NULL;
